# Generated by Django 4.0.4 on 2022-05-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companylogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cregnum', models.IntegerField()),
                ('cadd', models.TextField()),
                ('adrs', models.TextField()),
                ('contact', models.IntegerField()),
                ('website', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.login')),
            ],
        ),
    ]
