# Generated by Django 4.0.4 on 2022-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_companylogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
