# Generated by Django 4.0.4 on 2022-05-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_login_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylogin',
            name='adrs',
        ),
    ]
