# Generated by Django 4.0.4 on 2022-05-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_companylogin_adrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='addvacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jt', models.CharField(max_length=20)),
                ('vac', models.IntegerField()),
                ('date', models.TextField()),
                ('skills', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('dis', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.companylogin')),
            ],
        ),
    ]
