# Generated by Django 4.0.4 on 2022-05-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_addvacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvacancy',
            old_name='date',
            new_name='dateto',
        ),
        migrations.AddField(
            model_name='addvacancy',
            name='datefrom',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addvacancy',
            name='skills',
            field=models.TextField(),
        ),
    ]
