# Generated by Django 4.0.4 on 2022-06-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_date_addvacancy_dateto_addvacancy_datefrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jt', models.TextField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.companylogin')),
            ],
        ),
    ]
