# Generated by Django 4.0.4 on 2022-06-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_sendfeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvacancy',
            name='salary',
        ),
    ]
