# Generated by Django 4.0.4 on 2022-06-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_addvacancy_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expsalary', models.IntegerField()),
                ('cv', models.FileField(upload_to='cv')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.companylogin')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.employee')),
            ],
        ),
    ]
